version: '2'
services:
  web:
    build: ./commafeed-nginx-docker/
    ports:
      - 80:80
    links:
      - commafeed
  commafeed:
    build: ../commafeed-docker/
    ports:
     - 8082:8082
     - 8084:8084
    volumes:
     - /config
     - /data
     - /log
    links:
     - redis
     - db
  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
  db:
    image: postgres:9.6.2-alpine
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=sa
     - POSTGRES_USER=sa
     - POSTGRES_DB=commafeed
